import play.sbt.routes.RoutesKeys
import sbt.Def
import uk.gov.hmrc.DefaultBuildSettings
import uk.gov.hmrc.versioning.SbtGitVersioning.autoImport.majorVersion

lazy val appName: String = "secure-message-stub"

ThisBuild / majorVersion := 0
ThisBuild / scalaVersion := "2.13.12"


lazy val root = (project in file("."))
  .enablePlugins(PlayScala, SbtDistributablesPlugin, SbtSassify)
  .disablePlugins(JUnitXmlReportPlugin) //Required to prevent https://github.com/scalatest/scalatest/issues/1427
  .settings(DefaultBuildSettings.scalaSettings: _*)
  .settings(DefaultBuildSettings.defaultSettings(): _*)
  .settings(inConfig(Test)(testSettings): _*)
  .settings(ThisBuild / useSuperShell := false)
  .settings(
    name := appName,
    RoutesKeys.routesImport ++= Seq("models._", "controllers.binders._"),
    PlayKeys.playDefaultPort := 9202,
    libraryDependencies ++= AppDependencies(),
    retrieveManaged := true,
    // concatenate js
    Concat.groups := Seq(
      "javascripts/securemessagestub-app.js" ->
        group(Seq("javascripts/show-hide-content.js", "javascripts/securemessagestub.js"))
    ),
    // prevent removal of unused code which generates warning errors due to use of third-party libs
    pipelineStages := Seq(digest),
    // below line required to force asset pipeline to operate in dev rather than only prod
    Assets / pipelineStages := Seq(concat),
    // only compress files generated by concat
  )
  .settings(
    // suppress warnings in generated routes files & html for unused-imports
    scalacOptions += "-Wconf:src=routes/.*:s",
    scalacOptions += "-Wconf:src=html/.*:s"
  )
  .settings(ScoverageSettings())

lazy val testSettings: Seq[Def.Setting[_]] = Seq(
  fork := true,
  javaOptions ++= Seq(
    "-Dconfig.resource=test.application.conf"
  )
)

dependencyOverrides ++= AppDependencies()

Test / test := (Test / test)
  .dependsOn(scalafmtCheckAll)
  .value
